### ISSUE TITLE
Loving it!

### ISSUE THREAD

**Issue by BrianLakstins** [fabien-github/duplicati_dashboard#1]
Loving seeing my backups centrally reported!

I don't know what is being sent in JSON.

I renamed by backups so that they have unique names.  Computer name is probably not in JSON that is sent, so no way to separate by names.

What about list of files that failed or errors?  Is that in the JSON?  Is there any way to drill down to that info?

**Comment by fabien-github** [comment]
Hi Brian, thanks for the feedback.

I didn't remember all the json values in the report but I'm sure the hostname is not sent.

For the list of files that failed, I tried everything to get them with telegraf but it's not possible because they are in a nested json. So no, this information can't be retrieved. Fortunately, that was the only nested thing really valuable.

Fabien.
